services:
  postgres:
    image: postgres:15
    container_name: innogram-postgres
    environment:
      POSTGRES_DB: innogram
      POSTGRES_USER: innogram_user
      POSTGRES_PASSWORD: innogram_password
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - innogram-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U innogram_user -d innogram"]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: innogram-redis
    ports:
      - "6380:6379"
    volumes:
      - redis_data:/data
    networks:
      - innogram-network

  rabbitmq:
    image: rabbitmq:3-management
    container_name: innogram-rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: innogram
      RABBITMQ_DEFAULT_PASS: innogram_password
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - innogram-network

  core_microservice:
    image: core-microservice
    container_name: innogram-core
    ports:
      - "3001:3001"
    env_file:
      - .env
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_started
      rabbitmq:
        condition: service_started
    networks:
      - innogram-network

  # auth_microservice:
  #   build: ./apps/auth_microservice
  #   container_name: innogram-auth
  #   ports:
  #     - "3002:3002"
  #   depends_on:
  #     - auth_postgres
  #     - redis
  #   env_file:
  #     - .env
  #   networks:
  #     - innogram-network

volumes:
  postgres_data:
  auth_postgres_data:
  redis_data:

networks:
  innogram-network:
    driver: bridge
