version: "3.9"

services:
  postgres:
    image: postgres:15
    container_name: innogram-postgres
    environment:
      POSTGRES_DB: innogram
      POSTGRES_USER: innogram_user
      POSTGRES_PASSWORD: innogram_password
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - innogram-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U innogram_user -d innogram"]
      interval: 5s
      timeout: 5s
      retries: 10

  rabbitmq:
    image: rabbitmq:3-management
    container_name: innogram-rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: innogram
      RABBITMQ_DEFAULT_PASS: innogram_password
    networks:
      - innogram-network
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "ping"]
      interval: 5s
      timeout: 5s
      retries: 10

  core_microservice:
    build:
      context: .
      dockerfile: apps/core_microservice/Dockerfile
    container_name: innogram-core
    env_file:
      - .env.local
    ports:
      - "3001:3001"
    depends_on:
      postgres:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    networks:
      - innogram-network
    command: >
      sh -c "
      node dist/scripts/migrate.js &&
      node dist/main.js
      "

  auth_microservice:
    build:
      context: .
      dockerfile: apps/auth_microservice/Dockerfile
    container_name: innogram-auth
    env_file:
      - .env.local
    ports:
      - "3002:3002"
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - innogram-network
    command: >
      sh -c "
      node dist/main.js
      "

  notifications_consumer_microservice:
    build:
      context: .
      dockerfile: apps/notifications_consumer_microservice/Dockerfile
    container_name: innogram-notifications
    env_file:
      - .env.local
    ports:
      - "3003:3003"
    depends_on:
      rabbitmq:
        condition: service_healthy
      postgres:
        condition: service_healthy
    networks:
      - innogram-network
    command: >
      sh -c "
      node dist/main.js
      "

volumes:
  postgres_data:

networks:
  innogram-network:
    driver: bridge
